name: weather_app
description: "A Flutter weather app using flutter_bloc, geolocator, and weather package."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.4.0
  flutter: ^3.22.0

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8

  # Weather and location
  geolocator: ^11.0.0
  weather: ^3.2.1

  # State management
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5

  # Utilities
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/
